# ---
# jupyter:
#   jupytext:
#     cell_metadata_filter: ExecuteTime,collapsed,code_folding,-autoscroll
#     cell_metadata_json: true
#     formats: ipynb,py:percent
#     notebook_metadata_filter: all,-widgets,-varInspector
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.13.7
#   kernelspec:
#     display_name: Python 3 (ipykernel)
#     language: python
#     name: python3
#   language_info:
#     codemirror_mode:
#       name: ipython
#       version: 3
#     file_extension: .py
#     mimetype: text/x-python
#     name: python
#     nbconvert_exporter: python
#     pygments_lexer: ipython3
#     version: 3.8.8
#   latex_envs:
#     LaTeX_envs_menu_present: true
#     autoclose: false
#     autocomplete: true
#     bibliofile: biblio.bib
#     cite_by: apalike
#     current_citInitial: 1
#     eqLabelWithNumbers: true
#     eqNumInitial: 1
#     hotkeys:
#       equation: Ctrl-E
#       itemize: Ctrl-I
#     labels_anchors: false
#     latex_user_defs: false
#     report_style_numbering: false
#     user_envs_cfg: false
# ---

# %% [markdown]
# # How Large Are Transitory and Permanent Shocks?
#
# This notebook illustrates a simple method for measuring the size of transitory and permanent shocks for a set of households whose incomes are subject to those kinds of shocks

# %% {"code_folding": []}
# This cell has a bit of initial setup.
# You should substitute whatever setup you might need to address the questions below
import matplotlib.pyplot as plt
import numpy as np
import HARK
from copy import deepcopy
from HARK.utilities import plot_funcs
import statsmodels.api as sm

# %% [markdown]
# ## Income Process With Transitory and Permanent Shocks
#
# Assume that a household observes two income shocks at the beginning of each period.  Permanent income would be expected to grow by a factor $\Gamma_{t+1}$ in the absence of any shock (this could capture a life cycle profile of income, for example) but that growth is modified by a shock, $\Psi_{t+1}$:
# \begin{align}
#  P_{t+1} & = \Gamma_{t+1} P_{t}\Psi_{t+1}
# \end{align}
# whose expected (mean) value is $\mathbb{E}_{t}[\Psi_{t+1}]=1$.  Actual income received $Y$ is equal to permanent income $P$ multiplied by a transitory shock $\Theta$:
# \begin{align}
#  Y_{t+1} & = P_{t+1}\Theta_{t+1}
# \end{align}
# where again $\mathbb{E}_{t}[\Theta_{t+1}] = 1$.

# %% [markdown]
# For present purposes, we assume that the transitory and permanent shocks are independent.  The transitory shock has two components: A probability $\wp$ that the consumer is unemployed, in which case $\theta^{u}=\theta$, and a probability $(1-\wp)$ of a shock that is a lognormal with a mean chosen so that $\mathbb{E}_{t}[\theta_{t+n}]=1$.
#
# Using lower case variables for the logarithms of all variables above, the process can be written more conveniently as:
#
# \begin{align}
#  p_{t+1} & = \gamma_{t+1} + p_{t} + \psi_{t+1}
# \\ y_{t+1} & = p_{t+1} + \theta_{t+1}
# \end{align}
# where both lower-case Greek shocks are now white noise IID variables.
#
# ### Removing the Predictable Components
#
# In actual microeconomic data, the first step is to remove the predictable components of income growth (since we are interested here in the shocks).  This is traditionally done by estimating a model of income growth.  Restricting the sample to people of working age, one simply performs a regression:
#
# \begin{align}
#  y_{i} & = X_{i} \zeta + \epsilon_{i}
# \end{align}
#
# where person $i$ is characterized by observable variables $X_{i}$ in a given period, where $X$ includes usual variables like age, education, and other characteristics known to the person well in advance of the realization of income in the period in question.  The result is an estimate $\hat{\zeta}$ of the consequences of the exogenous variables $X$.  The predictable component of income growth is then obained from
# \begin{align}
#  \hat{\gamma}_{t,i} & = X_{t,i} \hat{\zeta}
# \end{align}
#
# ### Estimating The Variances 
#
# It will be notationally convenient to continue using the same variable names as before, where from here on out they are interpreted as having had the predictable component of income growth removed.  That is, we will assume that we now have data generated by a process like:
# \begin{align}
#  p_{t+1} & = p_{t} + \psi_{t+1}
# \\ y_{t+1} & = p_{t+1} + \theta_{t+1}
# \end{align}
#
# We can calculate a $d-$period difference in income as
# \begin{align}
#   y_{t+d} - y_{t} & = p_{t+d} - p_{t} + \theta_{t+d} - \theta_{t}
# \\ & =   \psi_{t+1} + \psi_{t+2} + ... \psi_{t+d} + \theta_{t+d} - \theta_{t}
# \end{align}
# and then we simply take the square of this to obtain:
# \begin{align}
#   (\Delta^{d}y)^{2} & = \left(\psi_{t+1} + \psi_{t+2} + ... \psi_{t+d} + \theta_{t+d} - \theta_{t}\right)^{2}
# \end{align}
# but since we have assumed that the $\psi$ and $\theta$ shocks are mutually and serially uncorrelated, the expectation of this simply becomes 
# \begin{align}
#   \mathbb{E}_{t}[(\Delta^{d}y)^{2}] & = \mathbb{E}_{t}[\psi_{t+1}^{2} + ... + \psi_{t+d}^{2} + 2 \theta^{2}]
# \\ & = d \sigma^{2}_{\psi} + 2 \sigma^{2}_\theta
# \end{align}
#
# This is an object that we can compute for any individual household.  We can then obtain an estimate of the two objects in question by calculating a set of squared differences in log income for all our households, and performing a very simple regression:
#
# \begin{align}
#   (\Delta^{d}y)^{2}_{i} & = \eta_{0} + d \eta_{1}
# \end{align}
# where $\nu_{1} = \sigma^{2}_{\psi}$ and $\nu_{0} = 2 \sigma^{2}_{\theta}$.
#
#
# ### The Intuition
#
# The intuition for this approach is pretty compelling:  Essentially, the consequence of permanent shocks is to make people get more and more different from each other continually over time as they accumulate permanent shocks.  So the degree to which the _changes_ in income keep increasing and increasing as time passes is a direct measure of the magnitude of the permanent shocks that are causing that divergence.  
#
# If there were no permanent shocks, then in year $t$ and in year $t+d$ the person will have experienced transitory shocks $\theta_{t}$ and $\theta_{t+d}$.  But the very _definition_ of "transitory" means that none of the shocks in intervening periods has any consequence for the difference in incomes between $t$ and $t+d$.  Only the two transitory shocks of those two years contribute.
#
# ### Two Small Caveats
#
# #### Time Aggregation
#
# If our data are measured at an annual frequency but income shocks can happen at any time during the year, then even if all shocks were permanent, an exercise like the one above, if conducted using annual data and using only three years of data (so, differences $\Delta^{1}$ and $\Delta^{2}$), would generate a biased answer due to the "time aggregation" problem ([Holbrook Working (1960)](doi:10.2307/1907574Copy); [Edmund Crawley (2020)](https://doi.org/10.1016/j.econlet.2020.108998).  Briefly, imagine two people who are identical up to the beginning of year $t$.  And they both experience identically sized shocks to permanent income in period $t$ -- but one experiences the shock on January 1, and the other on October 1.  Thus, the first person's income is boosted for the entire year by the shock; for this person, the method above would work.  But for the second person, only (1/4) of the year was spent earning the permanently higher level of income.  They would show some increment of income for the year $t$, but then would spend all of year $t+1$ at the higher level of income.  So, there would be a small change in income in year $t$ followed by a (predictable) larger increase in year $t+1$ -- which _looks like_ serial correlation in income growth.  In particular, this problem would manifest itself in a spurious first-order moving average (MA) component in a time series estimation that allowed for such a component.
#
# It can be shown that the problem goes away if only spans of years 2 or more are used.  That is, we have no problem if we use $\Delta^{3}$, $\Delta^{4}$, etc.  Indeed, it can be shown that the magnitude of the permanent shock can be estimated even when there is a _true_ MA component to the transitory shock, simply by restricting the data used to those that span intervals long enough for the MA component to have disappeared.
#
# #### A Lower Bound on $p$
#
# The process above assumes that permanent income can wander to arbitrarily large or small values.  But in practice, all countries that are sophisticated enough to have household datasets of the kind needed to measure these shocks, also have some degree of social insurance that prevents income from falling below some "necessity" level of income.  It can be shown that, if measured income is bounded below (cannot fall too far), then the estimated magnitude of the permanent shocks will be biased down and estimates of the magnitude of the transitory shock will be biased up.

# %% [markdown]
# # SOLUTION: Simulate and Estimate 
#
# The $\texttt{ConsIndShockModel}$ consumer type is hard-wired to experience permanent and transitory income shocks exactly like those described above.  
#
# 1. Construct a population of `ConsIndShockModel` consumers and simulate them
#    * Use the default parameter values 
# 1. Use the method above to calculate simulated 'empirical' estimates of the magnitude of the shocks
#    * Experiment to determine how large a population of consumers, and how long a span of time, you need to correctly recover the 'true' parameter values for the income process

# %% [markdown]
# The predicted coefficient for the number of lags, which estimates the variance of the permanent income shock, is approximately 0.0036 given the default parameters.
#
# I recover the variance of the permanent income shock ('PermShkVar') within 10\% of the predicted number (0.0032) with 10,000 agents ('AgentCount' = 10000) simulated over 100 periods ('T_sim' = 100). However, for some reason the relevant coefficient seems to increase with the number of agents.
#
# The predicted coefficient for the constant term, which estimates the variance of the permanent income shock multiplied by 2, is approximately 0.08 given the default parameters.
#
# I recover the variance of the transitory income shock, 'TranShkVar' * 2, to a coefficient of 0.085 with 1,000 agents ('AgentCount' = 1000) simulated over 125 periods ('T_sim' = 125). However, for some reason the constant coefficient seems to increase with the number of simulated periods.

# %%
# Import IndShockConsumerType
from HARK.ConsumptionSaving.ConsIndShockModel import IndShockConsumerType

# Define a dictionary with calibrated parameters
parameters = {
    "CRRA":1.0,                    # Coefficient of relative risk aversion 
    "Rfree":1.01/(1.0 - 1.0/160.0), # Survival probability,
    "PermGroFac":[1.000**0.25], # Permanent income growth factor (no perm growth),
    "PermGroFacAgg":1.0,
    "BoroCnstArt":0.0,
    "CubicBool":False,
    "vFuncBool":False,
    "PermShkStd":[(0.01*4/11)**0.5],  # Standard deviation of permanent shocks to income
    "PermShkCount":5,  # Number of points in permanent income shock grid
    "TranShkStd":[(0.01*4)**0.5],  # Standard deviation of transitory shocks to income,
    "TranShkCount":5,  # Number of points in transitory income shock grid
    "UnempPrb":0.07,  # Probability of unemployment while working
    "IncUnemp":0.15,  # Unemployment benefit replacement rate
    "UnempPrbRet":0.07,
    "IncUnempRet":0.15,
    "aXtraMin":0.00001,  # Minimum end-of-period assets in grid
    "aXtraMax":40,  # Maximum end-of-period assets in grid
    "aXtraCount":32,  # Number of points in assets grid
    "aXtraExtra":[None],
    "aXtraNestFac":3,  # Number of times to 'exponentially nest' when constructing assets grid
    "LivPrb":[1.0 - 1.0/160.0],  # Survival probability
    "DiscFac":0.97,             # Default intertemporal discount factor; dummy value, will be overwritten
    "cycles":0,
    "T_cycle":1,
    "T_retire":0,
    'T_sim':100,  # Number of periods to simulate (idiosyncratic shocks model, perpetual youth)
    'T_age': 100,
    'IndL': 10.0/9.0,  # Labor supply per individual (constant),
    'aNrmInitMean':np.log(0.00001),
    'aNrmInitStd':0.0,
    'pLvlInitMean':0.0,
    'pLvlInitStd':0.0,
    'AgentCount':1000
}

# %%
Test1 = IndShockConsumerType(**parameters)
Test1.solve()
Test1.track_vars = ['pLvl']
Test1.initialize_sim()
Test1.simulate()

# %%
print('The number of periods is ' + str(Test1.T_sim))
print('The number of agents is ' + str(Test1.AgentCount))

# %%
plt.plot(Test1.history['pLvl'][0:20,0:9])
plt.xlabel('Time')
plt.ylabel('Log Permanent Income')
plt.show()

# %%
# We are given Test1.history['pLvl'][:,:], 
# where the first component is the agent's consumption history across Test1.T_sim periods
# and the second component is the agent's index number given Test1.AgentCount agents

pLvlhist = Test1.history['pLvl']
pLvlhist[:,0]

# %%
# Now, generate the following dataset:
# 1. pLvldiff: Square of difference of period-(t+d) and period-t log permanent incomes of agent i (y_i,t+d - y_i,t)
# 2. lag: list of d's (number of periods between t and t+d)
# 3. constant term (vector of ones)
# As prescripted above, I set a minimum number of lags at 3 periods (minlag = 3)

pLvldiff = []
lag = []
minlag = 3

for i in np.arange(Test1.AgentCount):
    for s in np.arange(Test1.T_sim):
        for d in np.arange(minlag,Test1.T_sim-s):
            pLvldiffsq = (pLvlhist[s+d,i] - pLvlhist[s,i])**2
            pLvldiff.extend([pLvldiffsq])
            lag.extend([d])

# %%
np.size(pLvldiff), np.size(lag), np.size(np.ones(len(pLvldiff)))

# %%
# OLS regression of exogenous variables (lag "d" and constant term) on endogenous variable (pLvldiff)
y = np.transpose(pLvldiff)
X = np.transpose([lag, np.ones(len(pLvldiff))])
#X = sm.add_constant(X, prepend=False)
mod = sm.OLS(y,X)
res = mod.fit()
print(res.summary())

# %%
PermShkVar = (Test1.PermShkStd[0])**2
TranShkVar = (Test1.TranShkStd[0])**2

print('The variance of the permanent income shock is ' + str(PermShkVar))
print('The periods coefficient ("x1") that we ought to observe is ' + str(PermShkVar))
print('The periods coefficient ("x1") that we actually observe is ' + str(res.params[0]))

print('The variance of the transitory income shock is ' + str(TranShkVar))
print('The constant coefficient ("const") that we ought to observe is ' + str(TranShkVar*2))
print('The constant coefficient ("const") that we actually observe is ' + str(res.params[1]))
